export const interestsCategories = [
  {
    title: 'Relationship Goals',
    list: [
      'Casual Dating',
      'Serious Relationship',
      'Long-term Relationship',
      'Marriage',
      'Open Relationship',
      'Friends Only',
      'Networking',
      'Travel Partner',
    ],
  },
  {
    title: 'Hobbies & Interests',
    list: [
      'Fitness & Gym',
      'Outdoor Adventures',
      'Hiking & Camping',
      'Yoga & Meditation',
      'Cooking & Baking',
      'Music & Concerts',
      'Movies & TV Shows',
      'Reading & Books',
      'Gaming',
      'Art & Painting',
      'Photography',
      'Fashion & Style',
      'Dancing',
      'Traveling',
      'Tech & Gadgets',
      'Cars & Bikes',
    ],
  },
  {
    title: 'Personality & Lifestyle',
    list: [
      'Introvert',
      'Extrovert',
      'Night Owl',
      'Early Bird',
      'Workaholic',
      'Party Lover',
      'Animal Lover',
      'Foodie',
      'Coffee Addict',
      'Wine & Whiskey Enthusiast',
    ],
  },
  {
    title: 'Sports & Activities',
    list: [
      'Football',
      'Basketball',
      'Tennis',
      'Cycling',
      'Swimming',
      'Running',
      'Surfing',
      'Golf',
      'Martial Arts',
    ],
  },
  {
    title: 'Music & Arts',
    list: [
      'Pop Music',
      'Rock & Metal',
      'Jazz & Blues',
      'Classical Music',
      'EDM & Festivals',
      'Indie Music',
      'Theater & Broadway',
      'Stand-up Comedy',
    ],
  },
  {
    title: 'Social & Cultural Interests',
    list: [
      'Volunteering',
      'Environmental Activism',
      'Spirituality',
      'Astrology',
      'Politics & Debates',
    ],
  },
  {
    title: 'Pet Preferences',
    list: ['Dog Lover', 'Cat Lover', 'Exotic Pets', 'No Pets'],
  },
];
